version: '3'

networks:
    laravel:

services:
    webserver:
        container_name: ${APP_NAME}_webserver
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/project:delegated
        depends_on:
            - php
            - database_server
        networks:
            - laravel

    database_server:
        container_name: ${APP_NAME}_database
        image: mysql:8
        restart: unless-stopped
        volumes:
            - ./storage/app/mysql:/var/lib/mysql
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        container_name: ${APP_NAME}_php
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html/project:delegated
        networks:
            - laravel
    cron:
        container_name: ${APP_NAME}_cron
        build:
            context: ./dockerfiles
            dockerfile: cron.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www/html/project:delegated
        networks:
            - laravel
